# Generated by Django 4.2.5 on 2023-09-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('ingredients', models.TextField()),
                ('preparation', models.TextField()),
                ('description', models.TextField()),
                ('preparation_time', models.IntegerField(blank=True, null=True)),
                ('cooking_time', models.IntegerField(blank=True, null=True)),
                ('portions', models.IntegerField(blank=True, null=True)),
                ('_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
