# Generated by Django 4.2.5 on 2023-10-04 10:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import server.recipies.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('ingredients', models.TextField()),
                ('preparation', models.TextField()),
                ('description', models.TextField()),
                ('preparation_time', models.IntegerField(blank=True, null=True)),
                ('cooking_time', models.IntegerField(blank=True, null=True)),
                ('portions', models.IntegerField(blank=True, null=True)),
                ('_created_at', models.DateTimeField(auto_now_add=True)),
                ('_updated_at', models.DateTimeField(auto_now=True)),
                ('avg_rating', models.FloatField(default=0)),
                ('total_reviews', models.IntegerField(default=0)),
                ('category', models.ManyToManyField(to='recipies.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('description', models.CharField(max_length=250, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('recipie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='recipies.recipie')),
                ('review_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageUrl', models.ImageField(blank=True, null=True, upload_to=server.recipies.models.upload_to)),
                ('recipie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='recipies.recipie')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('recipie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipies.recipie')),
            ],
        ),
    ]
