# Generated by Django 4.2.5 on 2023-09-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('recipie', models.ManyToManyField(to='recipies.recipie')),
            ],
        ),
    ]
