# Generated by Django 4.2.5 on 2023-09-07 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0002_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='recipie',
        ),
    ]
