# Generated by Django 4.2.5 on 2023-09-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0003_remove_category_recipie'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipie',
            name='category',
            field=models.ManyToManyField(to='recipies.category'),
        ),
    ]
