# Generated by Django 4.2.5 on 2023-09-07 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0004_recipie_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageUrl', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='RecipieImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipies.photo')),
                ('recipie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='recipies.recipie')),
            ],
        ),
    ]
