# Generated by Django 4.2.5 on 2023-09-08 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0005_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='recipie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipies.recipie'),
        ),
    ]
