# Generated by Django 4.2.5 on 2023-09-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0006_alter_photo_recipie_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipie',
            name='_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
