# Generated by Django 4.2.5 on 2023-09-08 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0007_recipie__updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='recipie_id',
            new_name='recipie',
        ),
    ]
