# Generated by Django 4.2.5 on 2023-09-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0008_rename_recipie_id_photo_recipie'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipie',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
