# Generated by Django 4.2.5 on 2023-09-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0011_review_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipie',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
    ]
