# Generated by Django 4.2.5 on 2023-09-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0012_recipie_avg_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipie',
            name='total_reviews',
            field=models.IntegerField(default=0),
        ),
    ]
