# Generated by Django 4.2.5 on 2023-10-02 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0013_recipie_total_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='recipie',
        ),
        migrations.AddField(
            model_name='recipie',
            name='photo',
            field=models.ManyToManyField(to='recipies.photo'),
        ),
    ]
