# Generated by Django 4.2.5 on 2023-10-02 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0015_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='review_user',
            new_name='comment_user',
        ),
    ]
