# Generated by Django 4.2.5 on 2023-10-02 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0016_rename_review_user_comment_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipie',
            name='photo',
        ),
        migrations.AddField(
            model_name='photo',
            name='recipie',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='recipies.recipie'),
            preserve_default=False,
        ),
    ]
