# Generated by Django 4.2.5 on 2023-10-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_extendappuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendappuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('doNotShow', 'Do not show')], null=True),
        ),
    ]
